const Sdata = [
    {   
        id:1,
        sname: "DARK",
        imgscr: "https://wallpapercave.com/wp/wp4056410.jpg",
        title: "A netflix series",
        links: "https://www.netflix.com/in/title/80100172#:~:text=2017%20%7C%20TV%2DMA%20%7C%203,Baran%20bo%20Odar%2C%20Jantje%20Friese",
    },
    {
        id:2,
        sname: "LOVE IS BLIND",
        imgscr: "https://m.media-amazon.com/images/M/MV5BZGI2MTFiYjUtMjFhMS00ODY5LWJlNGEtZWIyNzNmNWU1NjU2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        title: "Anetflix TV series",
        links: "https://www.netflix.com/in/title/80996601",
    },
    {
        id:3,
        sname: "THE ROYAL TREATMENT",
        imgscr: "https://upload.wikimedia.org/wikipedia/en/4/42/The_Royal_Treatment.jpg",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/81228331",
    },
    {
        id:4,
        sname: "SWEET MAGNOLIAS",
        imgscr: "https://m.media-amazon.com/images/M/MV5BZjBmNTI2ZDEtOThhMy00OTkyLTg5Y2ItMTUxMzU4NWI1MzhhXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_FMjpg_UX1000_.jpg",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/80239866",
    },
    {
        id:5,
        sname: "THE CUPHEAD SHOW",
        imgscr: "https://i.ytimg.com/vi/VLyfaB2QAyM/maxresdefault.jpg",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/80239866",
    },
    {
        id:6,
        sname: "extra curricular",
        imgscr: "https://img.jakpost.net/c/2020/05/02/2020_05_02_94245_1588395372._large.jpg",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/80239866",
    },
    {
        id:7,
        sname: "All of us are Dead",
        imgscr: "https://www.whats-on-netflix.com/wp-content/uploads/2021/09/All-of-Us-Are-Dead-Date-Announcement-Netflix-0-24-screenshot.png",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/81237994?source=35",
    },
    {
        id:8,
        sname: "The Fame Game",
        imgscr: "https://jbt-en-images.s3.ap-south-1.amazonaws.com/wp-content/uploads/2022/01/27154200/the-fame-game-series.jpg",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/81133092",
    },
    {
        id:9,
        sname: "extra curricular",
        imgscr: "https://wallpapercave.com/wp/wp7418494.jpg",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/80239866",
    },
    {
        id:10,
        sname: "Juvenile Justice",
        imgscr: "https://i0.wp.com/dailyresearchplot.com/wp-content/uploads/2022/02/2-261.jpg?resize=1200%2C800&ssl=1",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/81312802?source=35",
    },
    {
        id:11,
        sname: "Thirty-Nine",
        imgscr: "https://img.i-scmp.com/cdn-cgi/image/fit=contain,width=1098,format=auto/sites/default/files/styles/1200x800/public/d8/images/canvas/2022/02/21/609f803c-caaa-42e4-a5dc-2ae76cc5a4f2_80874d45.jpg?itok=0SnTNwnT&v=1645411775",
        title: "A netflix movie",
        links: "https://www.netflix.com/in/title/81568400?source=35",
    }
];
export default Sdata;